                                              BY : GOLU KUMAR  CSE 4A5                                                .

* NumPy is a fundamental library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in scientific computing, data analysis, machine learning, and more. 

* Jupyter is an open-source web application that allows you to create and share documents containing live code, equations, visualizations, and narrative text. It supports various programming languages, including Python, R, and Julia. The name "Jupyter" is derived from the combination of the three programming languages it initially supported: Julia, Python, and R.

In [2]:
import numpy as np
print("Hello Lerner")
print("let's lern numpy with jupyter, shift+enter to next shell and execute this cell")

Hello Lerner
let's lern numpy with jupyter, shift+enter to next shell and execute this cell


In [3]:
arr = np.array([1,2,33,44], np.int8)
print(arr)
arr.dtype
arr[1] = 64  #updating value
arr[1]

[ 1  2 33 44]


64

# 1. Array creation : using python structure

In [4]:
listarray = np.array([[1,2,3,4],[11,22,33,44],[101,102,11,1]])
print(listarray)
print(listarray.dtype)
print(listarray.size)
print(listarray.shape)
listarray[1,2]
changed = listarray.reshape((4,3)) # note number of elements must be equal to previous shape
# NumPy arrays are immutable, so the reshape function returns a new reshaped array; it doesn't modify the original array in-place.
# so , we have to STORE further we can update the origional array
# for direct change here : listarray = listarray.reshape((4,3))
print(changed)
listarray = listarray.ravel() # covert into 1d array
print(listarray)
print(listarray.shape)

[[  1   2   3   4]
 [ 11  22  33  44]
 [101 102  11   1]]
int32
12
(3, 4)
[[  1   2   3]
 [  4  11  22]
 [ 33  44 101]
 [102  11   1]]
[  1   2   3   4  11  22  33  44 101 102  11   1]
(12,)


# 2. Array creation : using intrinsic numpy array creation

In [5]:
arr = np.zeros((3,4),np.int16) # by default according to my system float 64
print(arr)
print(arr.dtype)
print(arr.size)
print(arr.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int16
12
(3, 4)


In [6]:
rng = np.arange(5) # same as range
print(rng)
print(rng.dtype)
print(rng.shape)

lspace = np.linspace(1,2,10) # (from, where, numberOfElements) with equal space
print(lspace)
print(lspace.shape)

emp = np.empty((3,5)) #make empty array with random numbers
print(emp)
emp_like = np.empty_like(lspace)  # same like any pervious array
print(emp_like)

id = np.identity(6) # gives identity matrix
print(id)
print(id.shape)
print(id.dtype)


[0 1 2 3 4]
int32
(5,)
[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
(10,)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
(6, 6)
float64


In [7]:
import numpy as np
# numpy axis
# 1-d array = 1 axis (example x axis)
# 2-d array = 2 axis (example x,y axis)
# 3-d array = 3 axis (example x,y,z axis)
x = [[1,2,3],[4,5,6],[7,8,9]]
ar = np.array(x)
print(ar)
print(ar.sum(axis=0))  # axis=0 means downward rows
print(ar.sum(axis=1))  # axis=1 means left to right in cloumns

print(ar.T)  # T means transpose of the matrix

for item in ar.flat:  # .flat is used in iteration
    print(item)

print(ar.ndim)  # dimension here 2-d
print(ar.size)  # SIZE 
print(ar.nbytes)  # memory bytes consuming


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
1
2
3
4
5
6
7
8
9
2
9
36


In [8]:
one = np.array([1,30,4,56,7])
print(one.argmax())  # argmax() function return index of maximum element
print(one.argmin())  # argmin() funciton return index of minimum element
print(one.argsort()) #  return indices of ascending order as an array


3
0
[0 2 4 1 3]


In [9]:
print(ar.argmax(axis=0)) # indices of max of axis o
print(ar.argmax(axis=1)) # indices of max of axis 1
print(ar.argsort(axis=0)) # indices of max of axis 0 of ascending order
print(ar.argsort(axis=1)) # indices of max of axis 1 of ascending order


[2 2 2]
[2 2 2]
[[0 0 0]
 [1 1 1]
 [2 2 2]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [10]:
print(ar.ravel()) # in 1-d form
print(ar.reshape(9,1)) # changing shape


[1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [11]:
a = np.array([[1,6,3],[1,0,7],[2,3,8]])
b = np.array([[4,2,1],[4,6,1],[5,9,2]])
print(a+b)  # addition of 2 matrix , we can't do in list it will append
print(a*b)  # multiplication element wise


[[ 5  8  4]
 [ 5  6  8]
 [ 7 12 10]]
[[ 4 12  3]
 [ 4  0  7]
 [10 27 16]]


In [12]:
c = np.array([[1,6,3],[1,0,7],[2,3,8]])
print(c.sum())  # sum of all elements
print(c.max())  # max element
print(c.min())  # min element
print(np.sqrt(c)) # square root of each element of the array
print(np.where(c>7))  # return  array tuple condition matching
print(np.count_nonzero(a))  # return count
print(np.nonzero(a)) # return tuple indices of nonzero elements
print()

31
8
0
[[1.         2.44948974 1.73205081]
 [1.         0.         2.64575131]
 [1.41421356 1.73205081 2.82842712]]
(array([2], dtype=int64), array([2], dtype=int64))
8
(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 2, 0, 1, 2], dtype=int64))



In [13]:
import sys
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)
sys.getsizeof(1)*len(py_ar)  # space occupied by list of python array


112

In [14]:
np_ar.itemsize*np_ar.size # space occupied by the numpy
# this is why numpy is memory efficient . 

16

In [15]:
ar.tolist() # return array into form of list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]